spring:
  application:
    name: portapi-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: admin_route
          uri: lb://portapi-admin1
          predicates:
            - Path=/api/**
        - id: proxy_route
          uri: lb://portapi-proxy
          predicates:
            - Path=/**




server:
  port: 8080

gateway:
  secret: ${GATEWAY_SECRET:your-secret-key-here}

internal:
  secret: ${INTERNAL_SECRET:xHXYRaxYUJ6OYmFPPn0+j2aepYTWsxNzeG1vNwPnKLs=}

jwt:
  secret: Aoo/Lv+crFTY5wYzalGw5Pab6FVEYy/xnYZKGSjIvY4=
  expiration: 3600000
