spring:
  application:
    name: portapi-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: admin_route
          uri: lb://portapi-admin
          predicates:
            - Path=/api/**
        - id: proxy_route
          uri: lb://portapi-proxy
          predicates:
            - Path=/**

server:
  port: ${GATEWAY_PORT:8080}

gateway:
  secret: ${GATEWAY_SECRET}

internal:
  secret: ${INTERNAL_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}