server:
    port: 8080
spring:
  application:
    name: portapi-gateway

  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: http://localhost:8081
          predicates:
            - Path=/port/**
          filters:
            - StripPrefix=1
